storePassword=android-midas
keyPassword=android-midas
keyAlias=android-midas
storeFile=android-midas.jks

DSN="https://321f3cba20c334fb9952b6994ef1eb54@o4507926650159104.ingest.us.sentry.io/4508000518995968"

LINE_ID_PROD=2006581148
LINE_ID_UAT=2006582036

DEFAULT_WEB_CLIENT_ID_UAT="160194962688-virk8ghv9i9b3h252jebmrb2ns39fsp0.apps.googleusercontent.com"
DEFAULT_WEB_CLIENT_ID_PROD="160194962688-chu4re25s4kjhtl482a3jf82dh5judf9.apps.googleusercontent.com"

VN88_WEB_CLIENT_ID_UAT="160194962688-virk8ghv9i9b3h252jebmrb2ns39fsp0.apps.googleusercontent.com"
VN88_WEB_CLIENT_ID_PROD="160194962688-chu4re25s4kjhtl482a3jf82dh5judf9.apps.googleusercontent.com"

ALPHA88_WEB_CLIENT_ID_UAT="160194962688-a29jbhd5utcqk6fdhv84es5ii9v5t2qu.apps.googleusercontent.com"
ALPHA88_WEB_CLIENT_ID_PROD="160194962688-3bso110kiuds60c52i0gs2dmb18aiv3b.apps.googleusercontent.com"

GPWIN_ADJUST_TOKEN_UAT = "xslfoci29fr4"
GPWIN_ADJUST_TOKEN_PROD = ""

DEFAULT_ADJUST_TOKEN_UAT = ""
DEFAULT_ADJUST_TOKEN_PROD = ""


